# Generated by Django 6.0.3 on 2026-03-19 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='extra_data',
        ),
    ]
