# Generated by Django 6.0.3 on 2026-03-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_student_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='staff_type',
            field=models.CharField(choices=[('teaching', 'Teaching'), ('non_teaching', 'Non Teaching')], default='teaching', max_length=20),
        ),
    ]
